### ISSUE TITLE
busybox upstream?

### ISSUE THREAD

**Issue by f-andrey** [RIPE-NCC/ripe-atlas-software-probe#23]
What are the reasons for using a fork https://github.com/RIPE-NCC/ripe-atlas-probe-busybox
Why not use the mainstream?

**Comment by PhilipHomburg** [comment]
The fork contains the Atlas measurement code. In the early days of the V1 and V2 probes we had to use a single busybox otherwise we would run out of memory. 

There is a bit of a plan to remove all of the busybox code and end up with a repo that only contains Atlas code. But no work has been done on that.
