### ISSUE TITLE
Source code of master and releases seems to be diverging 

### ISSUE THREAD

**Issue by Janik-Haag** [RIPE-NCC/ripe-atlas-software-probe#83]
When trying to packaging the ripe-atals-software-probe for NixOS I noticed that the latest commit in master is a few months older then the newest release and that there is no other branch with the latest source. It also seems like the release order has gotten a bit mixed up between 5080 and 5084 and some versions are missing or the number was skipped. Is there a reason for the diverging code and if not would you mind updating master to the current state? And it would also be nice if some could explain the versioning :D

**Comment by Janik-Haag** [comment]
Okay thanks for your answer, and I guess that makes sense, but why isn't it documented on in the readme and why is there no development branch with the current development state?

**Comment by lukastribus** [comment]
In my follow up email I indeed asked to document this in README.

The development branch is private by design, as per the mailing list response.

**Comment by michel-stam** [comment]
Hi guys,

The documentation to the README has been added, its in the development tree. You will see it with the next release.

cheers,

Michel

**Comment by Janik-Haag** [comment]
Thank you, I'll mark this as resolved and wait for the next release.
Would you mind explaining the reasoning for having the develop branch hidden, this makes contributing to the project harder in my opinion.

**Comment by michel-stam** [comment]
Hi Janik,

The current strategy is that:
* the master branch is stable (release quality)
* the testing branch is the next release candidate
* the devel branch contains code which may make it into testing, or not. It can even be unstable.
* ticket branches which are branched off from devel

I am not keen on exposing devel given its volatile nature. Users may want to compile the latest and discover it does not work on the production backend. Patches may lose relevancy before release as well.

Similarly, testing may become the next release, but if a bug is found, it will not become a release. It is with this reason those pointers are not mirrored, to avoid confusion for people who are trying to decide what to build.

The tags are mirrored partially because of the way our internal GIT repository works. Also to show progress.

I'm happy to discuss mirroring if there is sufficient demand, this will need to be balanced against such as support or effect on the backend.

Feel free to reach out to me directly or on the atlas@ripe.net mailing list to further discuss?

Cheers,

Michel
